### ISSUE TITLE
Problem: StreamId needs custom marshaller and unmarshaller

### ISSUE THREAD

**Issue by MicBun** [truflation/tsn-sdk#17]

**Comment by MicBun** [comment]
1. How should the serialize and deserialize with the new struct?
2. Should `id` inside StreamId be exported so it can be serialized with json.Marshal?

**Comment by outerlook** [comment]
Hey @MicBun, is it possible to declare a custom marshaller and unmarshaller function instead? To keep id private

**Comment by MicBun** [comment]
> is it possible to declare a custom marshaller and unmarshaller function instead? To keep id private

I do think that possible

**Comment by MicBun** [comment]
closed as it turns out, the ones already built are already fulfilling, just need these extra lines and test succeeded https://github.com/truflation/tsn-sdk/pull/24/files#diff-da82d990cb51e3eb02a6af4489f6854e317074dcb9aa7592cf06494427e3c0ffR60
