### ISSUE TITLE
Question: are able to query from another wallet?

### ISSUE THREAD

**Issue by MicBun** [truflation/tsn-sdk#7]
https://github.com/truflation/tsn-sdk/blob/de34135f6e75087f5cfddb5bfa4f5d5eafb02a34/README.md?plain=1#L50

Is it expected? @outerlook 

```
type EthereumAddress struct {
	correctlyCreated bool <- private field
	hex              string <- private field
}
```

because, we can only read from our wallet only, not another wallet

this contradicts this comment on the docs:
```
	// if we intend to use streams from another provider, we create locators using the provider's address
```

**Comment by outerlook** [comment]
Yes, we should be able to query from another wallet; if someone needs that, they construct a locator manually:
```
thirdPartyStream := StreamLocator{
	StreamId:     someStreamId,
	DataProvider: otherAddress,
}
```

the user just need to make sure he's able to read from that stream. I.e. the stream is public or is private but granted wallet read access

**Comment by outerlook** [comment]
If someone needs to create another address, we use `NewEthereumAddressFromString` or `NewEthereumAddressFromBytes` which already checks if is in the correct format

**Comment by outerlook** [comment]
`OwnStreamLocator` seems to create confusion around that, more than it helps; we might want to get rid of it

**Comment by MicBun** [comment]
> If someone needs to create another address, we use NewEthereumAddressFromString or NewEthereumAddressFromBytes which already checks if is in the correct format

alright, that answered it

**Comment by outerlook** [comment]
:laughing: 

then it works fine?

**Comment by outerlook** [comment]
It would be nicer to say what wallet can't be read on the error, right?

**Comment by MicBun** [comment]
Ah yes, forget to mention that.

err doesn't catch the error.

To catch the error it needs to call waitTx.
It is inside one of the fields.

Maybe some extra conditional like --sync flag would do.
