### ISSUE TITLE
Problem: Validation failed because Signer is not returned on NewClient method.

### ISSUE THREAD

**Issue by MicBun** [truflation/tsn-sdk#9]
The signer here requires validation
https://github.com/truflation/tsn-sdk/blob/main/core/tsnclient/client.go#L18

but the Signer here has not returned
https://github.com/truflation/tsn-sdk/blob/main/core/tsnclient/client.go#L28

This will cause the validator to fail
https://github.com/truflation/tsn-utils/pull/1/files#diff-87c2475baa87005bd3a3001ec33f201feea23caddbbf5a2f249238a2bd32026dR15-R19

**Comment by MicBun** [comment]
Turns out Signer here can be assigned, but I think it can be handled in one go right?
```
	signer := &auth.EthPersonalSigner{Key: *pk}
	tsnClient, err := tsnclient.NewClient(ctx, cfg.TsnProvider, tsnclient.WithSigner(signer))
	if err != nil {
		panic(err)
	}
	tsnClient.Signer = signer
```

**Comment by brennanjl** [comment]
Construct the signer using an option:

```go
	privateKey, err := crypto.Secp256k1PrivateKeyFromHex("hex")

	clt, err := NewClient(ctx, "endpoint", &clientType.Options{
		Signer: &auth.EthPersonalSigner{
			Key: *privateKey,
		},
	})
```

Since Kwil supports any type of signature, you have to do it manually.

**Comment by MicBun** [comment]
> Since Kwil supports any type of signature, you have to do it manually.

Alright, thanks for the answer
